name: Deploy CKAN Status

on:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ github.repository == 'KSP-CKAN/NetKAN-status' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build CKAN Status
        run: npm install && npm run build-prod
      - name: Deploy CKAN Status to S3
        run: aws s3 sync ./dist/ s3://status.ksp-ckan.space
